# Generated by Django 3.2.25 on 2025-11-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VesselSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voyage', models.CharField(max_length=35)),
                ('status', models.CharField(choices=[('UCMP', 'UNCOMPLETED'), ('CMPL', 'COMPLETED')], default='UCMP', max_length=4)),
                ('arrival_berthed', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('is_phase_in', models.BooleanField(default=False)),
                ('direction', models.CharField(blank=True, choices=[('FORWARD', 'FORWARD'), ('BACKWARD', 'BACKWARD'), ('STRAIGHT', 'STRAIGHT')], max_length=25, null=True)),
                ('previous_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capacity_tracking.vesselschedule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacity_tracking.service')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacity_tracking.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='PortOfCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('etd', models.DateTimeField(blank=True, null=True)),
                ('ata', models.DateTimeField(blank=True, null=True)),
                ('atd', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ARRIVED', 'ARRIVED'), ('NOT ARRIVED', 'NOT ARRIVED'), ('SAILED', 'SAILED'), ('NOT SAILED', 'NOT SAILED'), ('OMITTED', 'OMITTED')], default='NOT SAILED', max_length=11)),
                ('port_status', models.CharField(choices=[('PHASE IN', 'PHASE IN'), ('PHASE OUT', 'PHASE OUT'), ('CUT AND RUN', 'CUT AND RUN'), ('ACTIVE', 'ACTIVE'), ('OMITTED', 'OMITTED')], default='ACTIVE', max_length=11)),
                ('call_no', models.CharField(blank=True, max_length=255, null=True)),
                ('via_no', models.CharField(blank=True, max_length=255, null=True)),
                ('via_date', models.DateTimeField(blank=True, null=True)),
                ('port_order', models.IntegerField(default=0)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='port_of_calls', related_query_name='port_of_calls', to='capacity_tracking.port')),
                ('to_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_port_of_calls', related_query_name='from_port_of_calls', to='capacity_tracking.port')),
                ('vessel_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='port_of_calls', related_query_name='port_of_calls', to='capacity_tracking.vesselschedule')),
            ],
        ),
    ]
