# Generated by Django 3.2.25 on 2025-11-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_criteria', models.CharField(choices=[('DEAD', 'Dead Freight contract'), ('SEGM', 'Segment Contract'), ('SEGMDIR', 'Segment Direct'), ('SEGMTHR', 'Segment Through Slot')], default='SEGMDIR', max_length=10)),
                ('call_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_openings_port_of_call', to='capacity_tracking.portofcall')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotWeightStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LADN', 'LADEN'), ('TRST', 'TRANSSHIPMENT'), ('EMTY', 'EMPTY')], default='LADN', max_length=4)),
                ('total_slots', models.IntegerField(default=0)),
                ('used_slots', models.IntegerField(default=0)),
                ('provisioned_slots', models.IntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('used_weight', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('provisioned_weight', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('slot_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.slotopening')),
            ],
        ),
        migrations.AddField(
            model_name='slotopening',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.vendor'),
        ),
        migrations.AddField(
            model_name='slotopening',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_opening_ports', to='capacity_tracking.port'),
        ),
        migrations.AddField(
            model_name='slotopening',
            name='to_call_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_opening_to_port_of_call', to='capacity_tracking.portofcall'),
        ),
        migrations.AddField(
            model_name='slotopening',
            name='to_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_opening_to_ports', to='capacity_tracking.port'),
        ),
        migrations.AddField(
            model_name='slotopening',
            name='to_vessel_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_opening_to_vessel_schedule', to='capacity_tracking.vesselschedule'),
        ),
        migrations.AddField(
            model_name='slotopening',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.vessel'),
        ),
        migrations.AddField(
            model_name='slotopening',
            name='vessel_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.vesselschedule'),
        ),
    ]
