# Generated by Django 3.2.25 on 2025-11-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_tracking', '0002_auto_20251129_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotweightstatus',
            name='rate_per_slot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
