# Generated by Django 3.2.25 on 2025-11-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_tracking', '0003_slotweightstatus_rate_per_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotweightstatus',
            name='rate_per_slot',
        ),
    ]
