# Generated by Django 3.2.25 on 2025-11-30 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_tracking', '0004_remove_slotweightstatus_rate_per_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('contract_criteria', models.CharField(choices=[('DEAD', 'Dead Freight contract'), ('SEGM', 'Segment Contract'), ('SEGMDIR', 'Segment Direct'), ('SEGMTHR', 'Segment Through Slot')], max_length=255)),
                ('slot_rate', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='SlotContractVesselScheduleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.slotcontract')),
                ('vessel_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.vesselschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ContractPortPairRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.slotcontract')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.port')),
                ('to_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_port_pair_to_ports', to='capacity_tracking.port')),
            ],
        ),
    ]
