# Generated by Django 3.2.25 on 2025-12-16 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_tracking', '0005_contractportpairrate_slotcontract_slotcontractvesselschedulemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofcall',
            name='vessel_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_of_calls', related_query_name='port_of_calls', to='capacity_tracking.vesselschedule'),
        ),
        migrations.CreateModel(
            name='SlotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(choices=[('DEAD', 'Dead Freight contract'), ('SEGM', 'Segment Contract'), ('SEGMDIR', 'Segment Direct'), ('SEGMTHR', 'Segment Through Slot')], max_length=10)),
                ('slots_needed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_request_from_ports', to='capacity_tracking.port')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.vendor')),
                ('to_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_request_to_ports', to='capacity_tracking.port')),
                ('vessel_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_tracking.vesselschedule')),
            ],
        ),
    ]
