# Generated by Django 3.2.25 on 2025-12-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_tracking', '0006_auto_20251216_0754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotRequest',
        ),
    ]
