# Generated by Django 3.2.25 on 2025-12-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_tracking', '0007_delete_slotrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselschedule',
            name='direction',
            field=models.CharField(blank=True, choices=[('FORWARD', 'FORWARD'), ('BACKWARD', 'BACKWARD'), ('STRAIGHT', 'STRAIGHT'), ('EAST', 'EAST'), ('WEST', 'WEST')], max_length=25, null=True),
        ),
    ]
