# Generated by Django 3.2.25 on 2025-12-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_tracking', '0008_alter_vesselschedule_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacity_tracking.port')),
            ],
        ),
        migrations.AddField(
            model_name='portofcall',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='port_of_calls', related_query_name='port_of_calls', to='capacity_tracking.terminal'),
        ),
    ]
